name: 'BuildContainer'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: |
            ghcr.io/matrixmind-cloud/aws-rds-operator:latest
      - run: docker push ghcr.io/matrixmind-cloud/aws-rds-operator:latest
